version: 'latest'
services:
  db:
    image: postgres
    restart: always
    environment:
      args:
        - POSTGRES_DATABASE=${POSTGRES_DATABASE}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      volumes:
        - pgdata:/var/lib/postgresql/data

    volumes:
      pgdata:

      adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080